services:
  db:
    image: postgres:15.4-alpine
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4:8.0
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-root}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - ${PGADMIN_PORT:-5050}:80

  mailpit:
    image: "axllent/mailpit:latest"
    ports:
      - "${FORWARD_MAILPIT_PORT:-1025}:1025"
      - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025"
    command: ["--smtp-auth-allow-insecure"]
    environment:
      MP_SMTP_AUTH: "rococo:1234"

  rabbitmq:
    image: rabbitmq:4.0.7-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: rococo
      RABBITMQ_DEFAULT_PASS: 1234

  app:
    depends_on:
      - db
      - pgadmin
      - rabbitmq
    build:
      context: .
    ports:
      - ${APP_PORT:-5000}:5000
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=5000 --debug
    environment:
      DB_HOST: db
      DB_USER: rococo
      DB_PASSWORD: 1234
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USERNAME: rococo
      RABBITMQ_PASSWORD: 1234

volumes:
  pgadmin:
  postgres:
