services:
  db:
    image: postgres:15.4-alpine
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4:8.0
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-root}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - ${PGADMIN_PORT:-5050}:80
  app:
    depends_on:
      - db
      - pgadmin
    build:
      context: .
    ports:
      - ${APP_PORT:-5000}:5000
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=5000 --debug
    environment:
      DB_HOST: db
      DB_USER: rococo
      DB_PASSWORD: 1234

volumes:
  pgadmin:
  postgres:
